# HW2
請寫一個程式可以輸入一個任意大小的矩陣，並具備以下功能：
1. 改變矩陣形狀 2.矩陣相乘（若無法相乘輸出 fail）3.轉置矩陣 4.矩陣輸出 5.結束
輸入：
首先輸入矩陣的大小、矩陣中的值，最後重複輸入功能代號

In [ ]:
import numpy as np
row, col = int(),int()

def reshape(arr):
    arr = arr.reshape(arr.shape[1], arr.shape[0])
    print(arr.shape)
    return arr
def multiple(arr):
    b = getArr()
    if arr.shape[1]!=b.shape[0]:
        print("fail")
        return arr
    else:
        new = np.dot(arr, b)
        return new
def transpose(arr):
    arr = arr.T
    return arr
def printArr(arr):
    print(arr)
    return arr
def end(arr):
    pass

def getArr():
    size = input()
    row = int(size.split(" ")[0])
    col = int(size.split(" ")[1])
    arr = []
    for i in range(row):
        col_val = input()
        arr.append([int(num) for num in col_val.split(" ")])

    a = np.array(arr)
    return a

switch={
    1: reshape,
    2: multiple,
    3: transpose,
    4: printArr,
    5: end
}

a = getArr()
request = 0
while request!=5:
    request = int(input("request: "))
    a = switch[request](a)


2 3
1 2 3
1 1 1
request: 1
(3, 2)
request: 4
[[1 2]
 [3 1]
 [1 1]]
request: 4
[[1 2]
 [3 1]
 [1 1]]
request: 2
3 2
2 2 3
1 1 1
1 2
fail
request: 4
[[1 2]
 [3 1]
 [1 1]]


In [10]:


print(a)

arr = a
a = arr.reshape(arr.shape[1], arr.shape[0])
print(a)

[[1 2 3]]
[[1]
 [2]
 [3]]
